In [1]:
import numpy as np

In [13]:
# numpy 배열
np.random.seed(0) # 동일한 세트의 시드 생성 가능



x1 = np.random.randint(10, size = 6) # 차원 개수
x2 = np.random.randint(10, size = (3,4)) # 차원의 크기
x3 = np.random.randint(10, size = (3,4,5)) # 전체 배열 크기


print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [12]:
# 차원의 개수
print("x3 dim :", x3.ndim)
# 각 차원의 크기
print("x3 shape :", x3.shape)
# 전체 배열 크기
print("x3 shape :", x3.size)

x3 dim : 3
x3 shape : (3, 4, 5)
x3 shape : 60


#### 배열 인덱싱
