# list 인덱싱

- 빈 리스트 생성 후 append method를 이용하여 데이터 추가
- 파이썬 리스트에는 콜론(:)을 이용한 ***슬라이싱*** 기능이 있음, 슬라이싱을 이용하면 범위를 지정해 부분 리스트를 얻을 수 있음.


In [1]:
a=[1,2,3,4,5,6]

c=a[3:5]
print(c)

# 기존 인덱싱은 [0,1,2,3,4]

b=a[-3:-1]
print(b)

# - 인덱싱은 [-5,-4,-3,-2,-1]

In [2]:
aa=[1,2,3,4,5,6,7,8,9,10]

ab=aa[::2]
ab
ac=aa[1::2]
ac

# Tuple

- 리스트는 [] 둘러싸며 튜플은 ()로 둘러쌈.
- 리스트 내의 원소를 변경할 수 있지만 튜플은 불가함

In [3]:
# 문자열 분리 a.split[',']

In [4]:
print("John's House")

In [5]:
print('Hello,\nBasic\t\tLecture')

# \n은 엔터키 대체
# \t는 tab 키 대체

In [6]:
license_plate = "24가 2210"

license_plate[4:9]

In [7]:
string="홀짝홀짝홀짝" 
                            
string[::2]

In [8]:
list_A=[1,2,3,4,5]

In [9]:
lenA = len(list_A)
print (lenA)

In [10]:
list_B = [1,2,3]

In [11]:
lenB = len(list_B)
print (lenB)

# len = len(list_A)로 지정시 len(list_B)은 오류가 뜸.
# overwriting을 해버리는데, 즉 변수 길이를 확인하는 len함수를 위에서 5로 지정해버림

3


In [12]:
string = "Hello/Machine/Deep/Learning"

In [13]:
List_A=(string[0:5],string[6:13],string[14:18],string[19:27])
List_A

('Hello', 'Machine', 'Deep', 'Learning')

In [14]:
list_B=[]
list_B.append(string[0:5])
list_B

['Hello']

In [15]:
list_C=[string.split("/")]
list_C

[['Hello', 'Machine', 'Deep', 'Learning']]

In [16]:
A="hello world"
aa =(A[:1]+"i"+ A[6:11])
aa

'hiworld'

In [17]:
str1 = "AB,CDE:FG,WX,Y".split(',')

str1

str1[-2]

str1[0][:-1]

str1[2:]

str1[:][:]

type(str)

# split 사용시 리스트가 됨.

type

In [18]:
str1 # str1 자체 프린트

['AB', 'CDE:FG', 'WX', 'Y']

In [19]:
str1[-2]  # -2 이므로 리스트 WX전체 인덱스 

'WX'

In [20]:
str1[0][:-1] # 리스트 AB 중 -2인 문자열 A 인덱스

'A'

In [21]:
str1[2:]   # 3번째 있는 WX부터 전체 인덱스

['WX', 'Y']

In [22]:
str1[:][:]  # 전체 리스트에 있는 전체 문자열 인덱스

['AB', 'CDE:FG', 'WX', 'Y']

# 조건문 if

- 파이썬은 코딩블럭을 표시하기 위해 들여쓰기를 사용함, 즉 java, c등과 같이 코딩블럭을 {}로 나타내지 않음.
- 조건문에는 if라는 키워드를 사용한다.
- if 다음에는 '조건'이 존재하는데 이 조건이 참(True)이면 들여쓰기한 문장이 실행된다. 
- if 문의 끝에는 콜론(:)을 입력한다.
- if 문의 조건이 참(True)일 때 실행되는 문장은 들여쓰기해야 한다. 

In [23]:
# elif : 실행해야 할 경우의 수가 2개 이상인 경우, ~ 그렇지 않고 ~ 이면 이라는 의미로 사용.

a = 1
if a>0 :
    print("a==",a)
    print("positive number")
elif a==0:  
    print("a==",a)
    print("zero")
else:
    print("a==",a)
    print("negative number")

a== 1
positive number


In [24]:
# **in** : 데이터 안에 조건에 해당하는게 있으면 true 없으면 false

list_data = [10,20,30,40,50]
dict_data = {'key1':1, 'key2':2}

if 45 in list_data : 
    print("45 is in list_data")
else : 
    print("45 is nat in list_data")
    
if "key1" in dict_data :
    print("dic_data")
else :
    print("not dic_data")

45 is nat in list_data
dic_data


# 반복문 for 문

- range() 함수 : 시작 값 ~ 마지막 값 -1

In [25]:
for data in range(10) : 
    print(data,"",end="")  
    
# end : 사용안할시 줄바꿈되어 나옴.

0 1 2 3 4 5 6 7 8 9 

In [26]:
company = ["Samsung","SK","LG"]
for ex in company:
    print("%s: Buy 10" % ex)

Samsung: Buy 10
SK: Buy 10
LG: Buy 10


In [27]:
for ex in company:
    print(ex +" "+"10%")

Samsung 10%
SK 10%
LG 10%


# While 문

- for 문과 같은 반복문
- while 문은 반복해야 할 횟수가 특별히 정해지지 않고 어떤 조건을 충족하는 동안만 실행될 때 주로 사용

In [28]:
i = 0
while i<=10:
    print(i,end=" ")
    i= i+1

0 1 2 3 4 5 6 7 8 9 10 

# list comprehension

- 리스트의 괄호 안에 for 루프를 사용하여 반복적으로 표현식을 실행하여 리스트 요소들을 정의하는 방법.

In [29]:
list_data=[x**2 for x in range(5)]
list_data

[0, 1, 4, 9, 16]

In [30]:
raw_data=[[1,10],[2,15],[3,30],[4,55]]

all_data = [x for x in raw_data]
x_data = [x[0] for x in raw_data]
y_data = [x[1] for x in raw_data]

print(all_data)
print(x_data)
print(y_data)

[[1, 10], [2, 15], [3, 30], [4, 55]]
[1, 2, 3, 4]
[10, 15, 30, 55]


In [31]:
apart=[[101,102,103,104],[201,202,203,204],[301,302,303,304],[401,402,403,404]]
arrears=[101,203,301,404]

for apt in apart:
    for apt1 in apt:
        if apt1 in arrears :
            print(str(apt1)+"호 배달 미납")
        else:
            print(str(apt1)+"호 배달 완료")



101호 배달 미납
102호 배달 완료
103호 배달 완료
104호 배달 완료
201호 배달 완료
202호 배달 완료
203호 배달 미납
204호 배달 완료
301호 배달 미납
302호 배달 완료
303호 배달 완료
304호 배달 완료
401호 배달 완료
402호 배달 완료
403호 배달 완료
404호 배달 미납


#  연습문제

In [32]:
# 짝수 출력하는 다음 코드를 List Comprehension으로 구분하시오.

even_number = []
for data in range(10):
    if data % 2 == 0:
        even_number.append(data)

print(even_number)

[0, 2, 4, 6, 8]


In [33]:
# my_list =["A","B","C","D"] 에서 파이썬 for 문과 슬라이싱을 이용하여 첫번째 데이터를 제외하고 나머지 데이터를 출력하시오.

my_list=["A","B","C","D"]
mlist= [my_list for my_list[1:4] in my_list]
   
print(my_list)

#틀림.



['A', 'A']


In [34]:
mylist=["A","B","C","D"]
for m1list in mylist:
    for m2list in m1list:
        for m3list in m2list:
            if m3list in mylist[1:]:
                print(m3list)

B
C
D


# 파이썬 class

- 파이썬 클래스는 class 키워드를 사용하여 자신만의 데이터 타입을 만들수있음.
- def __init__(self,x,y)
- #매개변수 생성



### 예외처리(Exception)하는 경우

- 1) I/O
- 2) 네트워크

- raise : 강제로 오류 내는 함수
- except : 오류를 받아 except문으로 구현하는 함수
- finally : 오류가 떠도 출력시키는 함수



In [35]:
class mytest:
    def hello(self) :  # self를 꼭 써줘야함.
        print("mytest hello method")

In [36]:
obj=mytest()
obj.hello()

mytest hello method


In [37]:
class point:
    def __Init__(self,x,y):
        self.x= x
        self.y= y
    def setx(self,new_x):
        self.x=new_x
    def sety(self,new_y):
        self.y=new_y


In [38]:
class MyCalc:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def summation(self):
        return self.a+self.b
    def subtract(self):
        return self.a-self.b
    def multiply(self):
        return self.a*self.b
    def divide(self):
        return self.a/self.b

In [39]:
ab=MyCalc(1,2)
print (ab.summation())

3


In [40]:
ab.subtract()

-1

In [41]:
ab.multiply()

2

In [42]:
ab.divide()  # mycalc(5,0)일 경우 5/0은 불가하므로 오류가 생김 따라서 예외처리를 해줘야함.

0.5

In [43]:
class MyCalc:
    def __init__(self,a,b):
        self.a=a
        self.b=b
        if(self.b==0):
            print("Division By Zero warring! y=0")
    def summation(self):
        return self.a+self.b
    def subtract(self):
        return self.a-self.b
    def multiply(self):
        return self.a*self.b
    def divide(self):
        if(self.b ==0):
            raise Exception("Error : Division By Zero")
        return self.a/self.b

In [44]:
try:                     # 예외처리를 사용시 프로그래밍 오류인지 수치 오류인지 파악하기 용이함.
    ab.divide()
except Exception as err:
    print(err)

# numpy

- vector/matrix 생성
- 행렬 곱
- broadcast -차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산
- index/slice/iterator

In [45]:
import numpy as np

A= np.array([1,2])
print(A)

[1 2]


In [46]:
from numpy import exp

result =exp(1)
print(result)

2.718281828459045


In [47]:
# ([]) 는 벡터로 ([[]])는 행렬로 나옴.

A=np.array([[1,0],[0,1]])
B=np.array([[0,1],[1,0]])

A+B

array([[1, 1],
       [1, 1]])

In [48]:
# shape - 행렬 형식 파악
# reshape - 행변환

C=np.array([[1,2,3],[4,5,6]])

print(C.shape)

D=C.reshape(6,1)
print(D)

F=C.reshape(-1,3)
print(F)

(2, 3)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]


In [49]:
A=np.array([1,2])
B=np.array([3,4])
T=np.array([5,6])

print(A)
print(B)
print(T)

print((1-A)*A)
print(T*(1-A)*A)

[1 2]
[3 4]
[5 6]
[ 0 -2]
[  0 -12]


In [50]:
C=np.array([[2],[3]])
D=np.array([[4],[5]])
P=np.array([[7],[8]])

E=np.array([2,3]).reshape(2,1)
print(E.ndim)
print(C)
print(D)
print(P)
print(E)


print((1-C)*C)
print(T*(1-C)*D)

2
[[2]
 [3]]
[[4]
 [5]]
[[7]
 [8]]
[[2]
 [3]]
[[-2]
 [-6]]
[[-20 -24]
 [-50 -60]]


In [51]:
# 행렬곱 : np.dot(a,b)