In [1]:
import numpy as np

### slicing

- numpy slicing의 특징<br>
리스트와 달리 행과 열 부분을 나눠서 slicing이 가능함.

In [2]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
# 1행 가져오기
print("1행 가져오기 : ",a[:1])

# 2행 가져오기
print("2행 가져오기 : ", a[:2])

# 1행의 2열부터 4열
print("1행의 2열부터 4열 :",a[0,1:4]) 

# 2행의 1열부터 3열
print("2행의 1열부터 3열 : ",a[1,0:3])

1행 가져오기 :  [[1 2 3 4 5]]
2행 가져오기 :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1행의 2열부터 4열 : [2 3 4]
2행의 1열부터 3열 :  [6 7 8]


### arange

- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [4]:
# list의 range와 같은 효과
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
# 컬럼이 5개인 array생성
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
np.arange(0,5,0.5) # (시작,끝,step)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
# 0으로 가득찬 ndarray 생성

np.zeros(shape = (10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

### random sampling

- 데이터 분포에 따른 sampling으로 array를 생성

In [9]:
# 균등분포
np.random.uniform(0,1,10).reshape(2,5)

array([[0.79464406, 0.15717982, 0.89941942, 0.26035502, 0.79995659],
       [0.13792028, 0.39272456, 0.42213761, 0.28011677, 0.01390136]])

In [11]:
# 정규분포
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.26264399, -0.64639609,  0.9169946 ,  2.66830197,  1.25872002],
       [-0.93062161,  0.27385487, -1.32010158, -0.44675329, -0.01850663]])

In [12]:
# sum

test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
test_array.sum(dtype = np.float)

55.0

In [19]:
# axis
test_array = np.arange(1,13).reshape(3,4) #(axis=0,axis=1)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
# 열을 기준으로 sum
test_array.sum(axis = 1)

array([10, 26, 42])

In [22]:
# 행을 기준으로 sum
test_array.sum(axis = 0)

array([15, 18, 21, 24])

### concatenate

- numpy array를 합치는 함수

In [25]:
a = np.array([1,2,3])
b = np.array([2,3,4])

print(a)
print(b)

[1 2 3]
[2 3 4]


In [29]:
# 1차원 배열을 옆으로 붙임
np.concatenate((a,b),axis = 0)

array([1, 2, 3, 2, 3, 4])

In [45]:
# 2개의 배열을 위에서 아래로 붙이기
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])

np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
# 2개의 배열을 옆으로 붙이기
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])

np.concatenate((a,b), axis = 1)

array([[1, 2, 3, 2, 3, 4]])

In [55]:
a = np.array([[1,2],[3,4]])
print(a)

b = np.array([[5,6]])
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [41]:
np.concatenate((a,b.T),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

### numpy 사칙 연산

In [71]:
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
# matrix + matrix 연산
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [69]:
# matrix - matrix 연산 
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
# 같은 위치에 있는 값들끼리 연산
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [75]:
# 행렬 곱셈시 dot 사용
test_a.dot(test_a.T)

array([[14., 32.],
       [32., 77.]])

In [77]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

print(test_a)
print(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [78]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### transpose

- 전치 행렬 구할때 사용

In [79]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
print(test_a.transpose())
print(test_a.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [81]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

### broadcasting

- shape이 다른 배열 간 연산을 지원하는 기능

In [84]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [85]:
# matrix + scalar 덧셈
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [87]:
# # matrix * scalar 곱셈
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [88]:
# matrix / scalar 나눗셈
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [89]:
# test_matrix 몫
test_matrix//0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [93]:
# test_matrix ** scalar 제곱

test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### numpy 비교 연산자

In [95]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
# any : 하나라도 조건에 만족한다면 true
np.any(a > 5),np.any(a < 0)

(True, False)

In [99]:
# all : 모두가 조건에 만족한다면 true
np.all(a > 5), np.all(a < 10)

(False, True)

### np.where

- 조건문으로 사용하며 조건에 해당하는 인덱스 출력

In [107]:
a = np.array([1,3,0])
a

array([1, 3, 0])

In [108]:
# a가 0보다 클 경우 3을, 작을 경우 2을 반환 
np.where(a > 0,3,2)

array([3, 3, 2])

In [110]:
# 조건에 성립하는 인덱스만 출력
np.where(a > 0)

(array([0, 1], dtype=int64),)

In [112]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### argmax & argmin

In [113]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
# argmax : array내 최대값의 인덱스 반환

a = np.array([1,2,4,5,6,12,14,15])
print(np.argmax(a))
print(a[np.argmax(a)])

7
15


In [117]:
# argmin : array내 최솟값의 인덱스 반환

print(np.argmin(a))
print(a[np.argmin(a)])

0
1


In [121]:
b = np.array([[1,2,3,4],[1,4,5,2],[9,1,3,1]])
b

array([[1, 2, 3, 4],
       [1, 4, 5, 2],
       [9, 1, 3, 1]])

In [122]:
# row를 기준으로 큰 값 찾기
np.argmax(b,axis = 1)

array([3, 2, 0], dtype=int64)

In [123]:
# column을 기준으로 큰 값 찾기
np.argmin(b,axis = 0)

array([0, 2, 0, 2], dtype=int64)