# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
# 넘파이 실행
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
# 넘파이 버젼 확인
print(np.__version__)

1.16.2


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
# null vector 10개로 채워진 array를 생성해라
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
## ??

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# numpy.을 활용하여 실행한다

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
# 5번째 위치의 숫자가 1인 10개 크기의 벡터를 만들어라
ex6 = np.zeros(10)
ex6[4] = 1
ex6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
# 10부터 49까지의 벡터를 만들어라
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
# 벡터를 반대로 나열하라
z = np.arange(1,50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
# 0부터 8까지 3*3 행렬을 만들어라
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
z = np.array([1,2,0,0,4,0])
np.nonzero(z)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
# 3*3의 단위행렬을 만들어라
np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)

# eye 사용하면 간단히 나옴....
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
# 랜덤 value를 가진 3*3*3크기의 배열을 만들어라
np.random.random((3,3,3))

array([[[0.78345078, 0.42285019, 0.23361727],
        [0.19855966, 0.01169573, 0.19155405],
        [0.99927462, 0.6832425 , 0.67870362]],

       [[0.92952946, 0.45742992, 0.19050388],
        [0.65330024, 0.77341446, 0.235584  ],
        [0.55633226, 0.02173366, 0.31441902]],

       [[0.10505235, 0.82506434, 0.06665269],
        [0.59183563, 0.80576027, 0.60387266],
        [0.86225945, 0.73696875, 0.19338106]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
# 10*10 크기의 랜덤한 배열을 만들고 최댓값과 최솟값을 찾아라
z = np.random.random((10,10))
# 최댓값
print(np.max(z))
# 최솟값
print(np.min(z))

0.9692177642042278
0.014759745469831276


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
# 크기가 30인 랜덤한 벡터를 만들고 평균 value를 찾아라
z = np.random.random(30)

# 벡터의 평균
np.mean(z)

0.4581019902795095

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
# 1로 0을 감싼 2차원 배열을 만들어라 
z = np.zeros((5,5))
z[:1]=1 
z[-1] = 1
z[:,0] = 1
z[:, -1] = 1
z

# np.ones라는 명령어도 존재한다!
z = np.ones((5,5))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
# 이번엔 1을 0으로 감싼 2차원 배열을 만들어라
z = np.zeros((7,7))
z[1:-1,1:-1] = 1
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
# np.nan : 알 수 없는, 정의할 수 없는 숫자
# np.inf : 무한대
print("0 * np.nan : nan")
print("np.nan == np.nan",":","false")
print("np.inf > np.nan : false")

0 * np.nan : nan
np.nan == np.nan : false
np.inf > np.nan : false


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
# 5*5의 행렬을 만들되, 행렬의 대각선 밑으로 1,2,3,4를 채워라
z = np.zeros((5,5))

# 대각행렬을 추출하는 np.diag를 활용
# 대각행렬에 +1을 더한 후, 1행을 더 생성
z + np.diag(1+np.arange(4),-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
# checkerboard pattern의 8*8 행렬 생성
z = np.zeros((8,8))
z
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
# (6,7,8)모양의 행렬에서 100번째 요인 (x,y,z) 위치 찾기
z = np.zeros((6,7,8))


np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
# fuction을 활용하여 checkerboard 패턴의 8*8행렬 생성
def make_array(x,y) :
    a = np.array([[x,y],[y,x]])
    ab = np.tile(a,(4,4))
    return ab

make_array(0,1)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
# 5*5 정규화 행렬 생성
np.random.randn(5,5)

array([[-0.31269728,  1.59543344, -0.2794231 , -0.36953047, -0.11963623],
       [ 0.37790261, -1.63374521, -0.54000434, -0.10831923, -0.16602758],
       [ 0.08555522, -0.25662418, -0.40197125,  1.86589743,  1.0009468 ],
       [-0.70393275,  1.00116529,  0.20193976, -0.83037597,  1.77806986],
       [-0.59210039, -1.41689315,  0.72570601,  0.39325128,  0.0727472 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
a = np.random.randn(5,5).dtype
a

dtype('float64')

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
# 5*3행렬에 3*2행렬 곱하기

a = np.array(np.arange(15)).reshape(5,3)
b = np.array(np.arange(6)).reshape(3,2)
print(a)
print(b)

# 행렬 곱셈
np.dot(a,b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
# 1차원 배열에서 3과 8사이 숫자는 -부호
a = np.array(np.arange(11))
print(a)
a = np.array(np.arange(11))
a[(a >= 3) & (a <= 8)] *= -1
a

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
import numpy as np
print(np.sum(range(5),-1)) # np.sum을 사용하여 합을 구할 수 있음.

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
z = np.random.randint(10)
print(z**z)
print(2 << z >> 2)
print(z < -z) # 적합하지않음
print(1j*z)
print(z/1/1)
print(z<z>z) # 적합하지않음

16777216
128
False
8j
8.0
False


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
import warnings 
warnings.filterwarnings('ignore')
print(np.array(0) / np.array(0)) # 나누기는 불가능
print(np.array(0) // np.array(0)) # 몫만 구하는건 가능
print(np.array([np.nan]).astype(int).astype(float)) 

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = np.random.randn(10) # 정규분포에서 추출
print(a)
print(np.ceil(a)) # 정수중 큰값으로 올림
print(np.round(a,0))

b = np.random.uniform(-10,100,10)
print(b)
print(np.ceil(b)) # 정수중 큰값으로 올림
print(np.round(b,0)) # 실수 0번째 자리까지 반올림

[-0.04165828  0.76316143  0.50923404  0.69056293  0.38255872  0.80445042
 -0.4646802   0.12880945 -0.44334796  0.65905438]
[-0.  1.  1.  1.  1.  1. -0.  1. -0.  1.]
[-0.  1.  1.  1.  0.  1. -0.  0. -0.  1.]
[ 1.66042045e+01 -4.11542669e-02  2.46004835e+01  5.87511942e+01
  3.53515459e+01  2.80677345e+01  3.41014909e+01  6.16532206e+01
 -3.24181357e+00  9.15805468e+01]
[17. -0. 25. 59. 36. 29. 35. 62. -3. 92.]
[17. -0. 25. 59. 35. 28. 34. 62. -3. 92.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.array(np.arange(10))
b = np.array(np.arange(5,15))

print(a)
print(b)
print(np.size(a))
print(np.size(b))

# 1차원 배열 간 교집합 찾기
np.intersect1d(a,b)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
10
10


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
# 31. 모든 numpy 경고를 무시하는 법
# np.seterr(all = 'ignore') 사용
defaults = np.seterr(all = 'ignore')
np.ones(1)/0

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
# 어제,오늘,내일 날짜를 얻는 법
yesterday = np.datetime64('today', 'D') - 1
today = np.datetime64('today','D')
tomorrow = np.datetime64('today', 'D') + 1

print('Yesterday : {0} \n'
     'Today : {1} \n'
      'Tomorrow : {2}'.format(yesterday,today,tomorrow))

Yesterday : 2021-03-02 
Today : 2021-03-03 
Tomorrow : 2021-03-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
# 2016년 7월의 모든 날을 얻는 법
np.arange('2016-07','2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
a = np.random.uniform(1,11,10).round(0)
b = np.random.uniform(1,11,10).round(0)
# np.add(a,b, out = a) -> add한 값을 a에 할당
# np.multiply(a*b) 과 np.dot의 결과값은 다름
print('np.add : \n{0} \n'
      'np.divide : \n{1} \n'
      'np.negative :\n{2}\n'
      'np.multiply : \n{3}'.format(np.add(a,b), np.divide(a,2),np.negative(a),np.multiply(a,b)))

# 합해서 b에 할당
np.add(a,b,out = b)
np.divide(a,2,out = a)
np.negative(a, out = a)
np.multiply(a,b,out = a)

print('((A+B)*(-A/2)) result : \n {}'.format(a))

np.add : 
[16. 16.  5. 16. 17.  7. 11. 12. 14. 20.] 
np.divide : 
[5.  4.  1.5 5.  4.5 2.5 1.  3.  5.  5. ] 
np.negative :
[-10.  -8.  -3. -10.  -9.  -5.  -2.  -6. -10. -10.]
np.multiply : 
[ 60.  64.   6.  60.  72.  10.  18.  36.  40. 100.]
((A+B)*(-A/2)) result : 
 [ -80.   -64.    -7.5  -80.   -76.5  -17.5  -11.   -36.   -70.  -100. ]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [37]:
# 5가지의 방법으로 임의의 배열에서 정수 부분 추출
a = np.random.uniform(0,15,10)
print(a)
print(np.ceil(a)) # a의 가장 높은 정수를 올림
print(np.round(a)) # a를 0의자리까지 반올림
print(np.floor(a)) # a의 가장 낮은 정수까지 내림
print(a - a % 1) # a에서 a나머지 제거
print(np.trunc(a)) # a에서 버림

[10.60784099 12.95756628  1.69147351 11.21849443  1.42427871 12.6979201
  4.92166664  6.15800575  2.69536529 11.11560269]
[11. 13.  2. 12.  2. 13.  5.  7.  3. 12.]
[11. 13.  2. 11.  1. 13.  5.  6.  3. 11.]
[10. 12.  1. 11.  1. 12.  4.  6.  2. 11.]
[10. 12.  1. 11.  1. 12.  4.  6.  2. 11.]
[10. 12.  1. 11.  1. 12.  4.  6.  2. 11.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
# 0부터 4의 범위로 이루어진 5*5크기의 행렬을 만들어라
a = np.zeros((5,5)) # 0으로 구성된 5*5 행렬
a += np.arange(5) # 브로드캐스팅으로 각 행에 [0,1,2,3,4] 더함

a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
# 10개의 정수 배열을 생성하는 제너레이터 함수를 만들어라
def generator() :
    for i in range(10) :
        yield i
    
new_array = np.fromiter(generator(), dtype = 'int')
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
# 0과 1을 제외한 0과 1 사이 10개의 배열을 만들어라
np.linspace(0,1,11, endpoint = False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
# 10개 크기의 배열을 만들고 정렬해라
a = np.random.randn(10)
np.sort(a)

array([-1.54514461, -1.49562687, -0.84309163, -0.38942505, -0.27508377,
       -0.06422899,  0.00656879,  0.41669911,  0.69159953,  1.38224477])

In [42]:
# 작은 배열을 np.sum보다 빨리 계산하는 법
import time

In [43]:
# 작은 배열을 np.sum보다 빨리 계산하는 법
a = np.random.randn(10)
start = time.time()
np.sum(a)
print("np.sum 계산 시간 : {0} \n" .format(time.time() - start))
print(np.sum(a))

np.sum 계산 시간 : 0.0 

3.6617913416353898


In [44]:
# np.add.reduce 사용
a = np.random.randn(10)
start = time.time()
# np.sum.reduce
np.add.reduce(a)
print("np.add.reduce 계산 시간 : {0} \n" .format(time.time() - start))
print(np.add.reduce(a))

np.add.reduce 계산 시간 : 0.0010020732879638672 

0.884603152610689


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [23]:
# 임의의 a와와 b배열이 같은지 확인하기

# 임의의 배열 생성
a = np.random.uniform(1,10,10).round(0)
b = np.random.uniform(1,10,10).round(0)
print("a,b 배열 :\n {0} \n {1}".format(a,b))

aa = np.random.randint(0,5,5)
bb = np.random.randint(0,5,5)

print("aa,bb 배열 :",'\n', aa,'\n',bb)
# np.array_equal 사용하여 2개의 배열이 같은지 확인
print(np.array_equal(a,b))

# np.allclose 사용하여 2개의 배열이 같은지 확인
print(np.allclose(aa,bb))

a,b 배열 :
 [1. 1. 1. 4. 6. 7. 3. 7. 4. 9.] 
 [ 3. 10.  6.  4.  6.  1.  4.  8.  9.  5.]
aa,bb 배열 : 
 [3 1 3 1 4] 
 [1 3 2 4 2]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [39]:
# 배열을 변경 불가능하게 만들기
a = np.random.randint(0,10,10).reshape(2,5)
print("a배열 : \n", a)

a.flags.writeable = False

# 배열 변경이 불가능해짐
try :
    a[1,1] = 5
    
except ValueError :
    print("배열 변경이 불가능합니다.")

a배열 : 
 [[1 2 3 0 6]
 [1 4 5 8 2]]
배열 변경이 불가능합니다.


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [92]:
# 데카르트 좌표를 대표하는 임의의 10*2 행렬을 극좌표계로 변환해라

def cart2pol(x,y) :
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y,x)
    return(rho,phi)

def pol2cart(rho,phi) :
    x = rho*np.cos(phi)
    y = rho*np.sin(phi)
    return(x,y)



print(cart2pol(1,1))
print(pol2cart(1,1))

import matplotlib.pyplot as plt

c2p = list(range(10))
print(c2p)

x = c2p[:5]
y = c2p[5:]
print(x,y)



(1.4142135623730951, 0.7853981633974483)
(0.5403023058681398, 0.8414709848078965)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4] [5, 6, 7, 8, 9]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)